fold_num: 0
# dataset_name: 'matbench_log_gvrh'

train_data: '/home/hongshuh/space_group_transformer/data/mp.csv'
test_data: '/home/hongshuh/space_group_transformer/data/wbm.csv'
# train_data: '/home/hongshuh/space_group_transformer/matbench_stable/fold1/train.csv'
# test_data: '/home/hongshuh/space_group_transformer/matbench_stable/fold1/test.csv'

pretrain_model: null 
pretrain_model: '/home/hongshuh/space_group_transformer/runs_contrast/May29_10-18-35/best.pth'
scaler: 'pt'
vocab_path: '/home/hongshuh/space_group_transformer/vocab.json'
device: 'cuda:2'
epochs: 200
batch_size: 128
lr: 0.00001
weight_decay: 0.01
warmup_ratio: 0.05
robust: False
# task: 'classification'
task: 'regression'
max_element: 20 
hidden_size: 768
max_position_embeddings: 40            # max position embeddings of Transformer
blocksize: 34                          # max length of sequences after tokenization
num_attention_heads: 12                 # number of attention heads in each hidden layer
num_hidden_layers: 8                   # number of hidden layers
hidden_dropout_prob: 0.1                # hidden layer dropout
attention_probs_dropout_prob: 0.1       # attention dropout
mlm_probability: 0.15                   # masked probability in mlm